# Generated by Django 5.0 on 2024-01-04 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0004_remove_usermember_course_usermember_course1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='course1',
        ),
        migrations.AddField(
            model_name='usermember',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clgapp.course'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
